// hoo_frontend/VueSrc/components/AnimationControls.vue
<template>
  <div id="animation">
    <div class="control">
      <button @click="rotate">Rotate</button>
      <button @click="random">Random</button>
      <button @click="stop">Stop</button>
    </div>
    <div class="control">
      <input id="trans-time" type="number" min="0" max="65535" v-model="transitionTime" />
      <label for="trans-time">Transition time</label>
    </div>
    <div class="control">
      <input id="hold-time" type="number" min="0" max="65535" v-model="holdTime" />
      <label for="hold-time">Hold time</label>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import { BASE_URL } from '@/common/constants';
import * as AnimationApi from '@/common/api/animations';

export default Vue.extend({
    name: 'animationControls',
    data() {
        const transitionTime: number = 10;
        const holdTime: number = 0;

        return {
            transitionTime,
            holdTime,
        };
    },
    methods: {
        async rotate(event: any) {
            await AnimationApi.rotate(this.transitionTime, this.holdTime);
        },
        async random(event: any) {
            await AnimationApi.random(this.transitionTime, this.holdTime);
        },
        async stop(event: any) {
            await AnimationApi.stop();
        },
    },
});
</script>

<style scoped>
#animation {
    display: inline-block;
    border: 1px solid gray;
    padding: 10px;
    width: 400px;
}
</style>

// hoo_frontend/src/components/AnimationControls.tsx
import React from 'react';
import * as AnimationApi from '../common/api/animations';

interface AnimationControlState {
    transitionTime: number ;
    holdTime: number;
}

export default class AnimationControls extends React.Component<{}, AnimationControlState> {
    constructor(props: {}) {
        super(props)

        this.state = {
            transitionTime: 10,
            holdTime: 0,
        }
    }

    render() {
        return(
            <div id="AnimationControls">
                <div className="control">
                    <button onClick={this.rotate}>Rotate</button>
                    <button onClick={this.random}>Random</button>
                    <button onClick={this.stop}>Stop</button>
                </div>
                <div className="control">
                    <input id="trans-time" type="number" min="0" max="65535" v-model="transitionTime" />
                    <label htmlFor="trans-time">Transition time</label>
                </div>
                <div className="control">
                    <input id="hold-time" type="number" min="0" max="65535" v-model="holdTime" />
                    <label htmlFor="hold-time">Hold time</label>
                </div>
            </div>
        );
    }

    async rotate() {
        await AnimationApi.rotate(this.state.transitionTime, this.state.holdTime);
    }
    
    async random() {
        await AnimationApi.random(this.state.transitionTime, this.state.holdTime);
    }
    
    async stop() {
        await AnimationApi.stop();
    }
}
